name: Analyze Multiple Rounds

on:
  workflow_dispatch:
    inputs:
      season:
        description: 'Season number'
        required: true
        type: number
      rounds:
        description: 'Comma-separated round numbers (e.g., 1,2,3)'
        required: true
        type: string
      depth:
        description: 'Stockfish depth (default: 15)'
        required: false
        default: '15'
        type: number

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        round: ${{ fromJson(format('[{0}]', github.event.inputs.rounds)) }}
      max-parallel: 3  # Analyze 3 rounds simultaneously
    timeout-minutes: 120

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y stockfish
          pip3 install python-chess stockfish

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Node dependencies
        run: npm ci

      - name: Analyze Round ${{ matrix.round }}
        run: |
          echo "Starting analysis for Season ${{ github.event.inputs.season }} Round ${{ matrix.round }}"
          echo "Depth: ${{ github.event.inputs.depth }}"
          echo "Start time: $(date)"

          cat data/season-${{ github.event.inputs.season }}-round-${{ matrix.round }}.pgn | \
            node scripts/generate-stats.js \
              --round ${{ matrix.round }} \
              --season ${{ github.event.inputs.season }} \
              --analyze \
              --depth ${{ github.event.inputs.depth }}

          echo "End time: $(date)"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: stats-round-${{ matrix.round }}
          path: public/stats/season-${{ github.event.inputs.season }}-round-${{ matrix.round }}.json

  commit:
    needs: analyze
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: Move artifacts to correct location
        run: |
          mkdir -p public/stats
          find artifacts -name "*.json" -exec cp {} public/stats/ \;
          ls -lh public/stats/

      - name: Commit results
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add public/stats/

          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "$(cat <<'EOF'
          Add Stockfish analysis for Season ${{ github.event.inputs.season }} rounds: ${{ github.event.inputs.rounds }}

          Analyzed with depth ${{ github.event.inputs.depth }}
          Generated by GitHub Actions
          EOF
          )"
            git push
          fi
