name: Generate Season Overview

on:
  schedule:
    # Run every Monday at 14:00 UTC (2pm)
    - cron: '0 14 * * 1'
  workflow_dispatch:
    inputs:
      season:
        description: 'Season number (defaults to current season)'
        required: false
        type: number

jobs:
  generate-overview:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Determine season
        id: detect
        run: |
          # Default to current season (Season 46)
          SEASON="${{ github.event.inputs.season }}"
          if [ -z "$SEASON" ]; then
            SEASON=46
          fi
          echo "season=$SEASON" >> $GITHUB_OUTPUT

          echo "Will generate overview for Season $SEASON"

      - name: Generate Season Overview
        run: |
          SEASON="${{ steps.detect.outputs.season }}"

          echo "Generating Season $SEASON overview..."
          echo "Start time: $(date)"

          node scripts/generate-overview.js --season $SEASON

          echo "End time: $(date)"

      - name: Verify output
        run: |
          SEASON="${{ steps.detect.outputs.season }}"
          OUTPUT_FILE="public/stats/season-${SEASON}-overview.json"

          if [ ! -f "$OUTPUT_FILE" ]; then
            echo "Error: Overview file not generated at $OUTPUT_FILE"
            exit 1
          fi
          echo "Generated overview file:"
          ls -lh "$OUTPUT_FILE"
          echo "File size: $(du -h "$OUTPUT_FILE" | cut -f1)"

          # Display summary
          echo ""
          echo "Overview Summary:"
          jq -r '"Rounds: \(.roundsIncluded | length) | Total Games: \(.aggregates.totalGames) | Players: \(.leaderboards.mostGames | length)"' "$OUTPUT_FILE"

      - name: Commit and push results
        run: |
          SEASON="${{ steps.detect.outputs.season }}"

          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add public/stats/season-${SEASON}-overview.json

          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "$(cat <<EOF
          Generate Season $SEASON overview statistics

          Auto-generated overview with team hall of fame
          EOF
          )"
            git pull --rebase
            git push
          fi

      - name: Summary
        if: always()
        run: |
          SEASON="${{ steps.detect.outputs.season }}"

          if [ -f "public/stats/season-${SEASON}-overview.json" ]; then
            echo "✅ Season $SEASON overview generated successfully!"
          else
            echo "❌ Failed to generate overview"
          fi
